<?php

namespace RedCircle\ConsoleProcessManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use RedCircle\ConsoleProcessManagerBundle\Entity\Call;

/**
 * CallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallRepository extends EntityRepository
{

    public function update(Call $call) {

        $em = $this->getEntityManager();
        $em->persist($call);
        $em->flush($call);

        return $call;
    }

}
